# Generated by Django 4.2.4 on 2023-08-24 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roulettelogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulettelog',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roulettelogs', to='fortune.roulettecell'),
        ),
        migrations.AlterField(
            model_name='roulettelog',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roulettelogs', to='fortune.round'),
        ),
    ]
